// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_QdshjsXsf_ophtKnQZyKog6RC15Pmw',
    appId: '1:545262679664:web:d58eb6e6e8b9a1577c26b5',
    messagingSenderId: '545262679664',
    projectId: 'phoneauth-ec2d3',
    authDomain: 'phoneauth-ec2d3.firebaseapp.com',
    storageBucket: 'phoneauth-ec2d3.appspot.com',
    measurementId: 'G-JVGDM7TVWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNQuWWICWgjBjfx_mBR9tEcenXcljc1k',
    appId: '1:545262679664:android:399a8651b24fef2c7c26b5',
    messagingSenderId: '545262679664',
    projectId: 'phoneauth-ec2d3',
    storageBucket: 'phoneauth-ec2d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSRxHiEunmx0qzDM5cxd5borKXT1dvVQ',
    appId: '1:545262679664:ios:ac9f3884f8da64dd7c26b5',
    messagingSenderId: '545262679664',
    projectId: 'phoneauth-ec2d3',
    storageBucket: 'phoneauth-ec2d3.appspot.com',
    iosClientId: '545262679664-4kev2pc4rh54kk4l9j49semk40kqka44.apps.googleusercontent.com',
    iosBundleId: 'com.mytestapp.example.mytestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSRxHiEunmx0qzDM5cxd5borKXT1dvVQ',
    appId: '1:545262679664:ios:ac9f3884f8da64dd7c26b5',
    messagingSenderId: '545262679664',
    projectId: 'phoneauth-ec2d3',
    storageBucket: 'phoneauth-ec2d3.appspot.com',
    iosClientId: '545262679664-4kev2pc4rh54kk4l9j49semk40kqka44.apps.googleusercontent.com',
    iosBundleId: 'com.mytestapp.example.mytestApp',
  );
}
